server:
  port: 8081

spring:
  application:
    name: distracted
  datasource:
    url: jdbc:sqlite:distracted.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    open-in-view: false
    properties:
      hibernate:
        type:
          preferred_instant_jdbc_type: TIMESTAMP
